from django.core.management.base import BaseCommand
from app.models import Job  # Update with your actual app name

class Command(BaseCommand):
    help = 'Populates the database with sample job data in Kazakh'

    def handle(self, *args, **options):
        Job.objects.all().delete()

        jobs_data = [
            {
                "title": "Маркетинг маманы",
                "company": "Apple",
                "location": "Астана",
                "job_type": "hybrid",
                "description": "Компаниямызға тәжірибелі маркетинг маманы қажет.",
                "salary": 120000.00,
                "jdata": ["3-5 жыл тәжірибе", "Үйден жұмыс"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Программист",
                "company": "Google",
                "location": "Алматы",
                "job_type": "remote",
                "description": "Қашықтан жұмыс істейтін Python программисті қажет.",
                "salary": 150000.00,
                "jdata": ["2-3 жыл тәжірибе", "Қашықтан", "Толық жұмыс"],
                "currency": "Доллар",
                "logo": None,
            },
            {
                "title": "Жобалар менеджері",
                "company": "Kazakh Telecom",
                "location": "Шымкент",
                "job_type": "office",
                "description": "Ішкі жобаларды басқаратын менеджер іздейміз.",
                "salary": 180000.00,
                "jdata": ["5+ жыл тәжірибе", "Кеңседе", "Командамен жұмыс"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "UI/UX дизайнер",
                "company": "Yandex",
                "location": "Алматы",
                "job_type": "remote",
                "description": "Тәжірибелі UI/UX дизайнер қажет.",
                "salary": 160000.00,
                "jdata": ["Figma", "3 жыл тәжірибе"],
                "currency": "Доллар",
                "logo": None,
            },
            {
                "title": "Мәліметтер талдаушы",
                "company": "BI Group",
                "location": "Астана",
                "job_type": "hybrid",
                "description": "Data аналитик іздейміз, SQL және Python қажет.",
                "salary": 140000.00,
                "jdata": ["SQL", "Python", "Талдау қабілеті"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Контент менеджер",
                "company": "Kolesa Group",
                "location": "Алматы",
                "job_type": "office",
                "description": "Контент жасау мен басқару.",
                "salary": 110000.00,
                "jdata": ["Копирайтинг", "SMM"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Қауіпсіздік инженері",
                "company": "Kaspi",
                "location": "Алматы",
                "job_type": "office",
                "description": "Ақпараттық қауіпсіздік инженері қажет.",
                "salary": 200000.00,
                "jdata": ["Киберқауіпсіздік", "Сертификаттар"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "HR маманы",
                "company": "Samruk-Kazyna",
                "location": "Атырау",
                "job_type": "full-time",
                "description": "Қызметкерлерді жалдау бойынша HR маманы.",
                "salary": 130000.00,
                "jdata": ["Жұмысқа қабылдау", "Ішкі саясат"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "DevOps инженер",
                "company": "Nazarbayev University",
                "location": "Астана",
                "job_type": "remote",
                "description": "AWS және Docker білетін DevOps маман.",
                "salary": 220000.00,
                "jdata": ["AWS", "Docker", "CI/CD"],
                "currency": "Евро",
                "logo": None,
            },
            {
                "title": "Backend әзірлеуші",
                "company": "ChocoFamily",
                "location": "Алматы",
                "job_type": "hybrid",
                "description": "Node.js немесе Django қолданатын әзірлеуші.",
                "salary": 180000.00,
                "jdata": ["Django", "REST API", "PostgreSQL"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "QA инженер",
                "company": "Beeline",
                "location": "Қарағанды",
                "job_type": "office",
                "description": "Жүйені тестілеу бойынша QA инженер.",
                "salary": 100000.00,
                "jdata": ["Автоматтандыру", "Selenium"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Финанс аналитик",
                "company": "Halyk Bank",
                "location": "Алматы",
                "job_type": "full-time",
                "description": "Қаржылық көрсеткіштерді талдау.",
                "salary": 170000.00,
                "jdata": ["Excel", "Финансовый анализ"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Журналист",
                "company": "Informburo",
                "location": "Алматы",
                "job_type": "remote",
                "description": "Жаңалықтарды зерттеу және жазу.",
                "salary": 90000.00,
                "jdata": ["Зерттеу", "Мәтін жазу"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Кеңсе әкімшісі",
                "company": "Nomad Insurance",
                "location": "Алматы",
                "job_type": "office",
                "description": "Кеңсе жұмыстарын ұйымдастыру.",
                "salary": 95000.00,
                "jdata": ["Ұйымдастырушылық қабілет", "1С білу"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "ІТ қолдау маманы",
                "company": "Technodom",
                "location": "Қостанай",
                "job_type": "full-time",
                "description": "ІТ қолдау және техникалық қызмет көрсету.",
                "salary": 100000.00,
                "jdata": ["Windows", "Желі"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Frontend әзірлеуші",
                "company": "Alser",
                "location": "Алматы",
                "job_type": "hybrid",
                "description": "React және Vue қолданатын фронтендші.",
                "salary": 160000.00,
                "jdata": ["React", "Vue", "HTML/CSS"],
                "currency": "Доллар",
                "logo": None,
            },
            {
                "title": "Контент жасаушы",
                "company": "Zharna",
                "location": "Алматы",
                "job_type": "remote",
                "description": "Instagram және TikTok үшін видео жасау.",
                "salary": 110000.00,
                "jdata": ["Монтаж", "Сценарий жазу"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "SMM менеджер",
                "company": "Freedom Finance",
                "location": "Астана",
                "job_type": "office",
                "description": "Әлеуметтік желіде жұмыс істеу.",
                "salary": 105000.00,
                "jdata": ["Instagram", "Meta Ads"],
                "currency": "Теңге",
                "logo": None,
            },
            {
                "title": "Жоба координаторы",
                "company": "Chevron",
                "location": "Атырау",
                "job_type": "hybrid",
                "description": "Мұнай және газ жобаларын басқару.",
                "salary": 210000.00,
                "jdata": ["Мұнай саласы", "Ағылшын тілі"],
                "currency": "Доллар",
                "logo": None,
            },
            {
                "title": "IT рекрутер",
                "company": "EPAM",
                "location": "Алматы",
                "job_type": "remote",
                "description": "IT мамандарды іздеу және сұхбаттасу.",
                "salary": 130000.00,
                "jdata": ["LinkedIn", "Сұхбат өткізу"],
                "currency": "Евро",
                "logo": None,
            },
        ]

        for job in jobs_data:
            Job.objects.create(**job)

        self.stdout.write(self.style.SUCCESS("✅ 20 жұмыс табысты енгізілді!"))
